sudo: false
language: node_js
branches:
    only:
        - master
    exclude:
        - test
notifications:
  email: false
node_js:
  - 6
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
